## exclude.R
##
## Reads a csv file generated by EDW query "2 - Exclusion Data"
## Evaluates data to determine which patients need to be excluded from the study
##
source("library.R")
source("limitIdentified.R")

## function to check if a file is already gzipped and will zip if not
gzip_files <- function(x) {
    if(isGzipped(x) == FALSE) {
        gzip(x)
    }
}

## compress medication data files
list.files("Data", full.names=TRUE) %>%
    lapply(gzip_files)

## Find patients who meet inclusion criteria
## read in vent data
raw.vent <- list.files("Data", pattern="^vent", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              event = factor(Clinical.Event),
              event.datetime = mdy_hms(Clinical.Event.Date.Result)) 

## remove patients with < 24 hours vent
## ?? cumulative vent time or continuous 24 hrs
## ?? should it be within a certain amount of time of icu admission
limit.vent <- group_by(raw.vent, pie.id) %>%
    arrange(event.datetime) %>%
    mutate(duration = as.numeric(difftime(lead(event.datetime), event.datetime, units="hours")),
           vent = ifelse(event == "Vent Start Time" & lead(event) == "Vent Stop Time", TRUE, NA)) %>%
    filter(duration >= 24,
           vent = TRUE) %>%
    select(pie.id) %>%
    distinct

## read in medication data and tidy variables
raw.meds.incl <- list.files("Data", pattern="^meds_include", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              admin.datetime = mdy_hms(Clinical.Event.End.Date.Time),
              med = str_to_lower(Clinical.Event),
              dose = as.numeric(Clinical.Event.Result),
              dose.units = factor(Clinical.Event.Result.Units),
              rate = as.numeric(Infusion.Rate),
              rate.units = factor(Infusion.Rate.Unit),
              route = factor(Route.of.Administration...Short))

## must have one of these
# lorazepam, midazolam, dexmedetomidine, propofol, fentanyl, hydromorphone, ketamine
limit.meds <- filter(raw.meds.incl, str_detect(med, "lorazepam|midazolam|dexmedetomidine|propofol|fentanyl|hydromorphone|ketamine"),
                     rate.units != "") %>%
    select(pie.id) %>%
    distinct

pts.eligible <- filter(pts.identified, pie.id %in% limit.vent$pie.id,
                       pie.id %in% limit.meds$pie.id) %>%
    select(pie.id) %>%
    distinct

## Remove patients meeting exlcusion criteria

## remove patients with more than one ICU admission
excl.mult.icu <- filter(pts.identified, pie.id %in% pts.eligible$pie.id) %>%
    group_by(pie.id) %>%
    summarize(admits = n()) %>%
    filter(admits > 1)

pts.include <- inner_join(pts.identified, pts.eligible, by="pie.id") %>%
    filter(!(pie.id %in% excl.mult.icu$pie.id))

## exclude patients who came from another facility
excl.transfer <- pts.include %>%
    filter(admit.type == "Direct") %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.transfer$pie.id))

## exclude patients who came from another ICU
tmp.icu <- c("Hermann 3 Shock Trauma Intensive Care Unit", 
             "Hermann 3 Transplant Surgical ICU",
             "HVI Cardiac Care Unit",
             "HVI Cardiovascular Intensive Care Unit",
             "Jones 7 J Elective Neuro ICU",
             "Jones 8 W Burn Unit")

excl.icu <- pts.include %>%
    filter(unit.from %in% tmp.icu) %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.icu$pie.id))

## remove patients with MICU stay < 1 day
excl.los <- pts.include %>%
    filter(micu.los < 1) %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.los$pie.id))

## exclude if any of these: cisatracurium, rocuronium, or vecuronium
excl.meds <- filter(raw.meds.incl, pie.id %in% pts.include$pie.id,
                    str_detect(med, "cisatracurium|rocuronium|vecuronium"),
                    rate.units != "") %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.meds$pie.id))

## labs which were included in query
levels.labs <- c("ur.preg", "ser.preg")

## read in lab data
raw.labs.excl <- list.files("Data", pattern="^labs_exclude", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              lab.datetime = mdy_hms(Clinical.Event.End.Date.Time),
              lab = factor(Clinical.Event),
              result = Clinical.Event.Result) %>%
    mutate(result = str_replace(result, "&gt;", ""),
           result = str_replace(result, "&lt;", ""),
           lab = str_to_lower(lab),
           lab = str_replace(lab, "u preg", "ur.preg"),
           lab = str_replace(lab, "s preg", "ser.preg"),
#            lab = str_replace(lab, "creatinine lvl", "scr"),
#            lab = str_replace(lab, "bili total", "t.bili"),
           lab = factor(lab, levels=levels.labs))

## check for pregnancy by lab test
excl.preg <- filter(raw.labs.excl, pie.id %in% pts.include$pie.id,
                    lab == "ur.preg" | lab == "ser.preg",
                    result == "Positive") %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.preg$pie.id))

## read in diagnosis codes
raw.diagnosis <- list.files("Data", pattern="^diagnosis", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              diag.code = ICD9.Diagnosis.Code,
              diag.type = factor(Diagnosis.Type),
              diag.primary = factor(Diagnosis.Code.Sequence))

## read in exclusion codes
ref.excl.codes <- read.csv("Lookup/exclusion_codes.csv", colClasses = "character")

## read in ICD9-CCS codes
ref.ccs.diag <- read.csv("Lookup/icd9_ccs_diagnosis.csv", colClasses="character") %>%
    transmute(ccs.code = as.numeric(CCS.CATEGORY),
              icd9.code = ICD9.CODE.FRMT) 

## find the ICD9 codes for the desired exclusions by CCS code
tmp.ccs <- filter(ref.excl.codes, type == "CCS") %>% 
    mutate(ccs.code = as.numeric(code)) %>%
    inner_join(ref.ccs.diag, by="ccs.code")

## ICD9 codes for non-CCS code exclusions
tmp.icd9 <- filter(ref.excl.codes, type=="ICD9") %>% 
    mutate(icd9.code = code) %>%
    inner_join(ref.ccs.diag, by="icd9.code")

## create one table with all ICD9 codes that should be excluded
tmp.excl.icd9 <- bind_rows(tmp.ccs, tmp.icd9) %>%
    select(disease.state, icd9.code) %>%
    group_by(disease.state)

## check for exclusions diagnosis: pregnant, alcohol withdrawal, cardiac arrest,
## status epilepticus
excl.diag <- filter(raw.diagnosis, pie.id %in% pts.include$pie.id,
                    diag.code %in% tmp.excl.icd9$icd9.code) %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.diag$pie.id))

## remove patients without any diagnosis codes
excl.nodiag <- filter(pts.include, !(pie.id %in% raw.diagnosis$pie.id)) %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.nodiag$pie.id))

## read in MPP data
raw.mpp <- list.files("Data", pattern="^mpp", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              mpp = factor(MPP..which.generated.order., exclude="")) 

## remove patients with alcohol withdrawal, comfort care, or hypothermia MPP
excl.mpp <- filter(raw.mpp, pie.id %in% pts.include$pie.id,
                   str_detect(mpp, "Alcohol Withdrawal|Comfort Care|Hypothermia")) %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.mpp$pie.id))

## read in procedure data to look for tracheostomy
raw.procs <- list.files("Data", pattern="^procedure", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              proc.code = ICD9.Procedure.Code,
              proc.date = mdy(Procedure.Date))

## trach procedure codes
trach <- c("31.1", "31.21", "31.29", "31.72", "31.74", "97.37")

excl.proc <- filter(raw.procs, pie.id %in% pts.include$pie.id,
                    proc.code %in% trach) %>%
    select(pie.id) %>%
    distinct

pts.include <- filter(pts.include, !(pie.id %in% excl.proc$pie.id))

## split the patients up into groups
edw.pie <- split(pts.include$pie.id, ceiling(seq_along(pts.include$pie.id)/1000))
## combine the id's in each group into a string, separated by semi-colon
edw.pie <- lapply(edw.pie, str_c, collapse=";")

print(edw.pie)
