## limitIdentified.R
##
## Reads a csv file generated by EDW query "1 - Identify Patients"
## Returns a list of PowerInsight Encounter Id's for patients who meet 
## criteria, to be used in next EDW query
##
source("library.R")

# set the directory containing the data
base.dir <- "U:/Research/Benzodiazepines in MICU/"

## read in the raw dosing service data files and join them, tidy the variables
pts.identified <- list.files(paste(base.dir, "Screen", sep = ""), pattern = "^micu_patients", full.names = TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              unit.from = factor(Person.Location...Nurse.Unit..From., exclude = ""),
              micu.los = as.numeric(Days.at.Location),
              admit.type = factor(Admit.Type),
              discharge.date = ymd_hms(Discharge.Date)) 

# using package readr
# library(readr)
# test <- list.files("Screen", pattern="^micu_patients", full.names=TRUE) %>%
#     lapply(read_csv, col_types = cols(col_character(), col_character(), 
#                                       col_character(), col_number(), 
#                                       col_factor(), col_datetime("%Y/%m/%d %H:%M:%S"))) %>%
#     bind_rows
    
pts.screen <- pts.identified %>%
    filter(discharge.date <= mdy("8/31/2015")) %>%
    select(pie.id) %>%
    distinct

## split the patients up into groups
edw.pie <- split(pts.screen$pie.id, ceiling(seq_along(pts.screen$pie.id) / 500))
## combine the id's in each group into a string, separated by semi-colon
edw.pie <- lapply(edw.pie, str_c, collapse = ";")

print(edw.pie)