## limitIdentified.R
##
## Reads a csv file generated by EDW query "1 - Identify Patients"
## Returns a list of PowerInsight Encounter Id's for patients who meet 
## criteria, to be used in next EDW query
##
library(dplyr)
library(stringr)

## read in the raw dosing service data files and join them, tidy the variables
pts.identified <- list.files("Screen", pattern="^micu_patients", full.names=TRUE) %>%
    lapply(read.csv, colClasses="character") %>%
    bind_rows %>%
    transmute(pie.id = PowerInsight.Encounter.Id,
              unit.from = factor(Person.Location...Nurse.Unit..From., exclude=""),
              micu.los = as.numeric(Days.at.Location),
              admit.type = factor(Admit.Type)) 

pts.screen <- select(pts.identified, pie.id) %>%
    distinct

## split the patients up into groups
edw.pie <- split(pts.identified$pie.id, ceiling(seq_along(pts.identified$pie.id)/1000))
## combine the id's in each group into a string, separated by semi-colon
edw.pie <- lapply(edw.pie, str_c, collapse=";")

print(edw.pie)